### ISSUE TITLE
Expand moult_plot function to allow plotting of predicted moult progression for categorical predictors eg sex

### ISSUE THREAD

**Issue by btohughhanmer** [pboesu/moultmcmc#9]
Something like https://github.com/BritishTrustForOrnithology/2021_Morrison_2015_moult_reanalysis/blob/main/analysis/moult_plot_colour_functions.R

**Comment by pboesu** [comment]
Ideally this should be handled via a predict method (https://github.com/pboesu/moultmcmc/issues/10).

**Comment by pboesu** [comment]
as of https://github.com/pboesu/moultmcmc/pull/16 `moult_plot()` takes a `newdata` argument which should address this
